MINIMALNA_DUZA_KWOTA = 3000
MINIMALNA_NISKA_KARTA = 5
MINIMALNA_NISKA_KWOTA = 10
WARTOSC_AS = 14
WARTOSC_JOKER = 11
KARTY_RUNDA_1 = 2
KARTY_FLOP = 5
KARTY_TURN = 6
KARTY_RIVER = 7

PODZIAL_SILNA_KOMBINACJA = 15
PODZIAL_SLABA_KOMBINACJA = 20
